//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.02.17 at 05:10:51 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://XML/customer", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.suresh;
